// <auto-generated />
using System;
using LogicService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicService.Model.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 101,
                            City = "Denver",
                            Country = "Usa",
                            Deleted = false,
                            PostalCode = "40022",
                            Street = "Cowstreet 13"
                        },
                        new
                        {
                            AddressId = 102,
                            City = "Hollywood",
                            Country = "United states",
                            Deleted = false,
                            PostalCode = "19922",
                            Street = "Hollywood drive 99a"
                        });
                });

            modelBuilder.Entity("LogicService.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeAddressId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostalAddressId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("HomeAddressId")
                        .IsUnique()
                        .HasFilter("[HomeAddressId] IS NOT NULL");

                    b.HasIndex("PostalAddressId")
                        .IsUnique()
                        .HasFilter("[PostalAddressId] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BirthDate = new DateTime(1961, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            EmailAddress = "tim.roth@logic.example.org",
                            FirstName = "Tim",
                            HomeAddressId = 101,
                            LastName = "Roth"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Deleted = false,
                            EmailAddress = "amanda.plummer@logic.example.org",
                            FirstName = "Amanda",
                            HomeAddressId = 102,
                            LastName = "Plummer"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Deleted = false,
                            EmailAddress = "laura.lovelace@logic.example.org",
                            FirstName = "Laura",
                            LastName = "Lovelace"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Deleted = false,
                            EmailAddress = "Unknown",
                            FirstName = "John",
                            LastName = "Travolta"
                        },
                        new
                        {
                            EmployeeId = 5,
                            BirthDate = new DateTime(1948, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            EmailAddress = "Unknown",
                            FirstName = "Samuel",
                            LastName = "Jackson"
                        });
                });

            modelBuilder.Entity("LogicService.Model.EmployeeEmployer", b =>
                {
                    b.Property<int>("EmployeeEmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeEmployerId"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeEmployerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployerId");

                    b.ToTable("EmployeeEmployer");
                });

            modelBuilder.Entity("LogicService.Model.Employer", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerId"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployerId");

                    b.ToTable("Employer");

                    b.HasData(
                        new
                        {
                            EmployerId = 1,
                            Deleted = false,
                            Email = "info@bkb.company",
                            Name = "Big Kahuna Burger",
                            Phone = "+0800bigkburger",
                            Website = "https://bkb.company"
                        },
                        new
                        {
                            EmployerId = 2,
                            Deleted = false,
                            Email = "info@jackrabbit.com",
                            Name = "Jack Rabbit Slim's",
                            Phone = "0800123123",
                            Website = ""
                        });
                });

            modelBuilder.Entity("LogicService.Model.Employee", b =>
                {
                    b.HasOne("LogicService.Model.Address", "HomeAddress")
                        .WithOne("EmployeeFromHomeAddress")
                        .HasForeignKey("LogicService.Model.Employee", "HomeAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogicService.Model.Address", "PostalAddress")
                        .WithOne("EmployeeFromPostalAddress")
                        .HasForeignKey("LogicService.Model.Employee", "PostalAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HomeAddress");

                    b.Navigation("PostalAddress");
                });

            modelBuilder.Entity("LogicService.Model.EmployeeEmployer", b =>
                {
                    b.HasOne("LogicService.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicService.Model.Employer", "Employer")
                        .WithMany("EmployeeEmployers")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("LogicService.Model.Address", b =>
                {
                    b.Navigation("EmployeeFromHomeAddress")
                        .IsRequired();

                    b.Navigation("EmployeeFromPostalAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicService.Model.Employer", b =>
                {
                    b.Navigation("EmployeeEmployers");
                });
#pragma warning restore 612, 618
        }
    }
}
